---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # We will uncomment these as we build them out
  - controllers/gateway-api
  - controllers/nginx-gateway
  # - networking
  # - storage
