apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-c-va1-uk
  namespace: ingress-gateway
spec:
  secretName: wildcard-va1-uk-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "*.va1.uk"
    - "va1.uk"
